print("Bem vindo ás aulas de sábado letivo")
print("Hoje vamos aprender sobre python")
print("Vamos começar com o básico: variáveis, tipos de dados")
print("Depois, vamos avançar para funções, módulos e bibliotecas")
print("Exercício1: crie uma variavel: \'nome' e \'até logo")